# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bipps_predict <- function(predx, predcoords, predblock, coords, parents, block_names, indexing, v_sampled, theta_sampled, lambda_sampled, beta_sampled, tausq_sampled, twonu, use_ps, verbose = FALSE, num_threads = 4L) {
    .Call(`_bipps_bipps_predict`, predx, predcoords, predblock, coords, parents, block_names, indexing, v_sampled, theta_sampled, lambda_sampled, beta_sampled, tausq_sampled, twonu, use_ps, verbose, num_threads)
}

Cov_matern <- function(x, y, sigmasq, phi, nu, tausq, same, nThreads = 1L) {
    .Call(`_bipps_Cov_matern`, x, y, sigmasq, phi, nu, tausq, same, nThreads)
}

Cov_matern2 <- function(x, y, phi, same, twonu) {
    .Call(`_bipps_Cov_matern2`, x, y, phi, same, twonu)
}

Cov_matern_h <- function(h, sigmasq, phi, nu, tausq) {
    .Call(`_bipps_Cov_matern_h`, h, sigmasq, phi, nu, tausq)
}

Cov_powexp_h <- function(h, sigmasq, phi, nu, tausq) {
    .Call(`_bipps_Cov_powexp_h`, h, sigmasq, phi, nu, tausq)
}

gneiting2002_h <- function(h, u, a, c, beta) {
    .Call(`_bipps_gneiting2002_h`, h, u, a, c, beta)
}

kernp_xx <- function(Xcoords, kweights) {
    .Call(`_bipps_kernp_xx`, Xcoords, kweights)
}

kernp_xy <- function(Xcoords, Ycoords, kweights) {
    .Call(`_bipps_kernp_xy`, Xcoords, Ycoords, kweights)
}

blanket <- function(parents, children, names, block_ct_obs) {
    .Call(`_bipps_blanket`, parents, children, names, block_ct_obs)
}

coloring <- function(blanket, block_names, block_ct_obs) {
    .Call(`_bipps_coloring`, blanket, block_names, block_ct_obs)
}

kthresholdscp <- function(x, k) {
    .Call(`_bipps_kthresholdscp`, x, k)
}

part_axis_parallel <- function(coords, Mv, n_threads, verbose = FALSE) {
    .Call(`_bipps_part_axis_parallel`, coords, Mv, n_threads, verbose)
}

part_axis_parallel_fixed <- function(coords, thresholds, n_threads) {
    .Call(`_bipps_part_axis_parallel_fixed`, coords, thresholds, n_threads)
}

mesh_graph_cpp <- function(layers_descr, Mv, verbose = TRUE, both_spatial_axes = TRUE, n_threads = 1L) {
    .Call(`_bipps_mesh_graph_cpp`, layers_descr, Mv, verbose, both_spatial_axes, n_threads)
}

cube_from_df <- function(indices, values) {
    .Call(`_bipps_cube_from_df`, indices, values)
}

knn_naive <- function(x, search_here, weights) {
    .Call(`_bipps_knn_naive`, x, search_here, weights)
}

mesh_graph_cpp3 <- function(blocks_descr) {
    .Call(`_bipps_mesh_graph_cpp3`, blocks_descr)
}

mesh_graph_hyper <- function(bucbl, bavail, na_which, centroids, avcentroids, avblocks, k = 1L) {
    .Call(`_bipps_mesh_graph_hyper`, bucbl, bavail, na_which, centroids, avcentroids, avblocks, k)
}

repeat_centroid_perturb <- function(x, times) {
    .Call(`_bipps_repeat_centroid_perturb`, x, times)
}

multi_bipps_mcmc <- function(y_list, family, X_list, coords, k, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, beta_Vi, matern_twonu, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, mcmc_startfrom = 0L, num_threads = 1L, which_hmc = 0L, adapting = FALSE, use_ps = TRUE, verbose = FALSE, debug = FALSE, print_every = FALSE, low_mem = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_lambda = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_bipps_multi_bipps_mcmc`, y_list, family, X_list, coords, k, parents, children, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, beta_Vi, matern_twonu, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, mcmc_startfrom, num_threads, which_hmc, adapting, use_ps, verbose, debug, print_every, low_mem, sample_beta, sample_tausq, sample_lambda, sample_theta, sample_w)
}

cube_tcrossprod <- function(x) {
    .Call(`_bipps_cube_tcrossprod`, x)
}

cube_correl_from_lambda <- function(lambda_mcmc) {
    .Call(`_bipps_cube_correl_from_lambda`, lambda_mcmc)
}

summary_list_mean <- function(x, n_threads = 1L) {
    .Call(`_bipps_summary_list_mean`, x, n_threads)
}

summary_list_q <- function(x, q, n_threads = 1L) {
    .Call(`_bipps_summary_list_q`, x, q, n_threads)
}

waic_test_runner <- function(log_likelihood) {
    .Call(`_bipps_waic_test_runner`, log_likelihood)
}

